Repository 1Shubham7/Wife-Predictor-v2, pull requests merged in 2024-10, with the labels that each got.

#136 Added title and made it dynamic with input #132
  package-lock.json
  src/App.css
  src/components/Confirm.js
  src/components/bestbutton.css
Labels: GSSoC, Level 1

#141 Just added few validation in Checkbox and button
  public/index.html
  src/components/Confirm.js
Labels: gssoc-ext, Level 1, hacktoberfest

#154 [UI Enhancements]: Local Storage, Responsive CSS, and Response Regeneration
  src/App.css
  src/components/Confirm.js
  src/components/My.css
  src/components/photo.css
  src/index.css
Labels: gssoc-ext, Level 2, hacktoberfest, hacktoberfest-accepted
